### ISSUE TITLE
sft 阶段loss异常增高

### ISSUE THREAD

**Issue by WangRongsheng** [jingyaogong/minimind-v#16]
![image](https://github.com/user-attachments/assets/afc41722-9776-4726-ab14-8a7226ed977f)

sft阶段跑一会loss就升高，而且越来越高。

**Comment by jingyaogong** [comment]
![image](https://github.com/user-attachments/assets/a2349edf-0a01-4d9a-b92b-ebbd761a1bdf)

epoch内的iteration之间数据也不一样啊，这不能称之为"loss就升高，而且越来越高"啊

**Comment by jingyaogong** [comment]
![image](https://github.com/user-attachments/assets/89b903ee-54cf-4a92-8b2d-f67ff256add4)

epoch内的iteration间数据也不一样啊，这不能称之为 "loss就升高，而且越来越高"

**Comment by jingyaogong** [comment]
![image](https://github.com/user-attachments/assets/89b903ee-54cf-4a92-8b2d-f67ff256add4)

同一个epoch内的i任意两个teration间数据分布完全不一样
这不能称之为 "loss就升高，而且越来越高"

**Comment by jingyaogong** [comment]
ok, 其它任何问题欢迎继续交流指正~😊
