### ISSUE TITLE
AMP训练-数据类型选择问题

### ISSUE THREAD

**Issue by chongkuiqi** [jingyaogong/minimind-v#24]
您好！

在2-sft_vlm.py文件中设置混合精度训练时，代码如下:
```python
ctx = nullcontext() if device_type == "cpu" else torch.cuda.amp.autocast()
```
这里没有设置float16或bfloat16，默认是torch.float16，指定为torch.bfloat16会不会更好一些？如下：
```python
ctx = nullcontext() if device_type == "cpu" else torch.cuda.amp.autocast(dtype=torch.bfloat16)
```

**Comment by jingyaogong** [comment]
我印象里必须V100以上架构才可以

GPU≤20系不支持bfloat16，那指定该类型不起作用，会自动回退到float32

`torch.cuda.amp.autocast()` 默认是float16兼容更好一点，所以这里暂时不变了

可以自行更换 `dtype=torch.bfloat16`
