### ISSUE TITLE
windows 平台下 dim 设置为 512 loss值没有变化，换成768可以的

### ISSUE THREAD

**Issue by gaoshan0007** [jingyaogong/minimind-v#4]
我遇到一个问题，在windows平台下 loss 值一直不变, 都是 8.766
代码只改了 torch==2.4.0 ， 其他都保持和主库一致，但是我把dim值改为 768就正常了，

512：
<img width="449" alt="35e62725874a036db5acc7311fdb685" src="https://github.com/user-attachments/assets/c421b849-3e7d-4300-b8ee-1ae82f8cef50">

768：
![image](https://github.com/user-attachments/assets/287ea27d-8a7a-4ed0-ad13-295aad3a0641)

**Comment by gaoshan0007** [comment]
换成自己的512_llm.pth也还是有问题，没搞懂了，希望大佬可以解答一下，非常感谢~~~

**Comment by jingyaogong** [comment]
> 换成自己的512_llm.pth也还是有问题，没搞懂了，希望大佬可以解答一下，非常感谢~~~

确实有点奇怪

lr前者是0.0002，保持和第二个0.0004一样试试呢

loss现在只保留了3位小数，可以开到6位小数，看看loss是否真的完全没变化。

**Comment by gaoshan0007** [comment]
感谢大佬回复！

我改成6位小数 和 0.0004了，貌似的确还是没变。 
![image](https://github.com/user-attachments/assets/0ba42f2b-847b-400e-842e-bc42752518ad)



> 另外，512+8和768+16，你这里看起来是dim 768 + 8 layers的吧，相当于只加载了前8层的权重变成新模型了，后8层没用到

是的，我只是测试一下

**Comment by jingyaogong** [comment]
> 感谢大佬回复！
> 
> 我改成6位小数 和 0.0004了，貌似的确还是没变。 ![image](https://private-user-images.githubusercontent.com/1872704/374071298-0ba42f2b-847b-400e-842e-bc42752518ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNTEzMjYsIm5iZiI6MTcyODM1MTAyNiwicGF0aCI6Ii8xODcyNzA0LzM3NDA3MTI5OC0wYmE0MmYyYi04NDdiLTQwMGUtODQyZS1iYzQyNzUyNTE4YWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDhUMDEzMDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGU3MTczNDE0Nzg4MDkwNzJhZjc5MTZjMWQyZTIyYjY5YjQ1MDFjNjc1NDczNTVjZWYxMDlmNTFlZTE5MjI5ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.KhAhZJnC5Ybvsj59028kokV75pdHy9Ppw2uHWm7n0ug)
> 
> > 另外，512+8和768+16，你这里看起来是dim 768 + 8 layers的吧，相当于只加载了前8层的权重变成新模型了，后8层没用到
> 
> 是的，我只是测试一下

确实奇怪，可能是权重文件损坏

重新上传了 `512_llm.pth` 和 `512_vlm_pretrain.pth` ([百度网盘](https://pan.baidu.com/s/1LE1SPoPYGS7VNtT1tpf7DA?pwd=6666) or [HuggingFace](https://huggingface.co/datasets/jingyaogong/minimind-v_dataset/tree/main/out))

**Comment by gaoshan0007** [comment]
替换文件后正常了！ 看来的确是权重文件的问题

再次感谢！

**Comment by jingyaogong** [comment]
> 替换文件后正常了！ 看来的确是权重文件的问题
> 
> 再次感谢！

No Thanks, Feel Free
有任何问题欢迎继续交流😊🤝~~
